language: android
android:
  components:
     - platform-tools
     - tools
     - build-tools-23.0.3
     - build-tools-24.0.3
     - android-24

  licenses:
    - 'android-sdk-license.*'
    - 'android-sdk-preview-license-.+'
    - 'google-gdk-license-.+'
    - 'extra-google-google_play_services'
    - 'extra-google-m2repository'
    - 'extra-android-m2repository'

jdk:
  - oraclejdk8

sudo: false

before_install:
 - chmod +x gradlew
 - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
 - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

script: './gradlew clean check'

cache:
  directories:
    - $HOME/.gradle